title: Lifetime Intermediate
theme: jekyll-theme-minimal
logo: /assets/TRM_headshot_circle.jpg
description: [Personal Page of Talal Mufti](https://www.linkedin.com/in/talalmufti/)
show_downloads: false