title: Lifetime Intermediate
theme: jekyll-theme-minimal
logo: /assets/images/TRM_headshot_circle.jpg
show_downloads: false

# Your name to show in the footer
author: Some Person

###############################################
# --- List of links in the navigation bar --- #
###############################################

navbar-links:
  About Me: "aboutme"
  Resources:
    - Beautiful Jekyll: "https://beautifuljekyll.com"
    - Learn markdown: "https://www.markdowntutorial.com/"